# Generated by Django 3.2.4 on 2021-06-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=122)),
                ('source_acc_no', models.CharField(max_length=122)),
                ('Current_balance', models.PositiveIntegerField()),
                ('money_deposit', models.PositiveIntegerField()),
                ('destination_name', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
